import { runMigrations } from '@/database/migrations';
import { NodeSQLiteAdapter } from '@/database/node-adapter';
import { ActivitiesRepository, ActivityStepsRepository, LookupRepository, TrainingSessionsRepository } from '@/database/repositories';
import { bootstrapLocalUser, seedLookups } from '@/database/seeds';
import type { StepType } from '@/database/types';
import { calculateEstimatedDuration, type EditorBlock, groupConsecutiveSteps, removeEditorStep, ungroupBlock, updateBlockRepeatCount, updateEditorStep } from '@/training/editor';

async function setup() {
  const database = new NodeSQLiteAdapter(); await runMigrations(database); await seedLookups(database);
  const userId = await bootstrapLocalUser(database); const lookups = new LookupRepository(database); await lookups.carregar();
  return { database, userId, lookups, trainings: new TrainingSessionsRepository(database, lookups), activities: new ActivitiesRepository(database, lookups) };
}

const type = (id: number, slug: StepType['slug'], name: string): StepType => ({ id, slug, name, description: null, is_active: true, created_at: new Date(), updated_at: new Date() });
const run = type(1, 'run', 'Corrida'); const walk = type(2, 'walk', 'Caminhada');
const draft = (): EditorBlock[] => [
  { key: 'a', repeatCount: 1, steps: [{ key: 's1', stepType: run, durationSeconds: 120, instructions: null }] },
  { key: 'b', repeatCount: 1, steps: [{ key: 's2', stepType: walk, durationSeconds: 120, instructions: null }] },
  { key: 'c', repeatCount: 1, steps: [{ key: 's3', stepType: run, durationSeconds: 300, instructions: null }] },
];

describe('fase 16 — blocos e duração', () => {
  it('agrupar 2 etapas em 6 repetições grava 1 bloco e 2 etapas', async () => { const { database, userId, trainings } = await setup(); const grouped = groupConsecutiveSteps(draft(), ['s1', 's2'], 6, 'g'); const saved = await trainings.salvar({ user_id: userId, name: 'Intervalado', blocks: grouped.map(block => ({ repeat_count: block.repeatCount, steps: block.steps.map(step => ({ step_type_slug: step.stepType.slug, duration_seconds: step.durationSeconds })) })) }); expect(saved.blocks[0]).toMatchObject({ repeat_count: 6 }); expect(saved.blocks[0]!.steps).toHaveLength(2); database.close(); });
  it('repeat_count 1 é rejeitado no agrupamento', () => expect(() => groupConsecutiveSteps(draft(), ['s1', 's2'], 1)).toThrow('O bloco precisa repetir ao menos 2 vezes'));
  it('etapas não consecutivas não podem ser agrupadas', () => expect(() => groupConsecutiveSteps(draft(), ['s1', 's3'], 2)).toThrow('Selecione etapas consecutivas'));
  it('desagrupar preserva a ordem e cada etapa vira bloco simples', () => { const blocks = ungroupBlock(groupConsecutiveSteps(draft(), ['s1', 's2'], 6, 'g'), 'g'); expect(blocks.map(block => block.steps[0]!.key)).toEqual(['s1', 's2', 's3']); expect(blocks.map(block => block.repeatCount)).toEqual([1, 1, 1]); expect(calculateEstimatedDuration(blocks)).toBe(540); });
  it('o treino canônico soma 2040 s e alterar repeat_count altera a duração', () => { const blocks = [{ ...draft()[2]!, steps: [{ ...draft()[2]!.steps[0]!, durationSeconds: 300 }] }, groupConsecutiveSteps(draft(), ['s1', 's2'], 6, 'g')[0]!, { ...draft()[2]! }]; expect(calculateEstimatedDuration(blocks)).toBe(2040); expect(calculateEstimatedDuration(blocks.map(block => block.key === 'g' ? { ...block, repeatCount: 2 } : block))).toBe(1080); });
  it('alterar tipo, duração e repetições recalcula imediatamente', () => { const grouped = groupConsecutiveSteps(draft(), ['s1', 's2'], 2, 'g'); const changedStep = updateEditorStep(grouped, 's1', { stepType: walk, durationSeconds: 180, instructions: 'Leve' }); const changedBlock = updateBlockRepeatCount(changedStep, 'g', 3); expect(changedBlock[0]!.steps[0]).toMatchObject({ stepType: walk, durationSeconds: 180, instructions: 'Leve' }); expect(calculateEstimatedDuration(changedBlock)).toBe(1200); });
  it('remover etapa recalcula imediatamente', () => { const blocks = draft(); expect(calculateEstimatedDuration(blocks)).toBe(540); expect(calculateEstimatedDuration(removeEditorStep(blocks, 'b', 's2'))).toBe(420); });
});

describe('fase 16 — persistência e validações', () => {
  it('treino sem etapas não é salvo; nome vazio não é salvo; duração zero é rejeitada', async () => { const { database, userId, trainings } = await setup(); await expect(trainings.salvar({ user_id: userId, name: 'Vazio', blocks: [] })).rejects.toThrow(); await expect(trainings.salvar({ user_id: userId, name: ' ', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 1 }] }] })).rejects.toThrow(); await expect(trainings.salvar({ user_id: userId, name: 'Zero', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 0 }] }] })).rejects.toThrow(); database.close(); });
  it('o valor materializado bate com o calculado e posições são contíguas', async () => { const { database, userId, trainings } = await setup(); const saved = await trainings.salvar({ user_id: userId, name: 'Canônico', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'walk', duration_seconds: 300 }] }, { repeat_count: 6, steps: [{ step_type_slug: 'run', duration_seconds: 120 }, { step_type_slug: 'walk', duration_seconds: 120 }] }, { repeat_count: 1, steps: [{ step_type_slug: 'walk', duration_seconds: 300 }] }] }); expect(saved.estimated_duration_seconds).toBe(2040); expect(saved.blocks.map(block => block.position)).toEqual([0, 1, 2]); expect(saved.blocks[1]!.steps.map(step => step.position)).toEqual([0, 1]); database.close(); });
  it('etapa removida na UI é removida do banco', async () => { const { database, userId, trainings } = await setup(); const original = await trainings.salvar({ user_id: userId, name: 'Dois', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 60 }] }, { repeat_count: 1, steps: [{ step_type_slug: 'walk', duration_seconds: 60 }] }] }); const edited = await trainings.salvar({ id: original.id, user_id: userId, name: 'Um', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 60 }] }] }); expect(edited.blocks).toHaveLength(1); expect((await database.all('SELECT * FROM training_steps'))).toHaveLength(1); database.close(); });
  it('falha na gravação não deixa treino parcial', async () => { const { database, userId, trainings } = await setup(); const runStatement = database.run.bind(database); database.run = async (sql, params) => { if (sql.startsWith('INSERT INTO training_steps')) throw new Error('falha injetada'); return runStatement(sql, params); }; await expect(trainings.salvar({ user_id: userId, name: 'Parcial', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 60 }] }] })).rejects.toThrow('falha injetada'); expect(await database.all('SELECT * FROM training_sessions')).toEqual([]); expect(await database.all('SELECT * FROM training_blocks')).toEqual([]); expect(await database.all('SELECT * FROM training_steps')).toEqual([]); database.close(); });
  it('editar treino não reescreve activity_steps nem o nome histórico', async () => { const { database, userId, trainings, activities, lookups } = await setup(); const training = await trainings.salvar({ user_id: userId, name: 'Original', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 60, instructions: 'Leve' }] }] }); const activity = await activities.criar({ user_id: userId, activity_type_slug: 'structured', training_session_id: training.id, training_session_name: training.name, started_at: new Date() }); const stepRepo = new ActivityStepsRepository(database, lookups); const source = training.blocks[0]!.steps[0]!; await stepRepo.criarSnapshot(activity.id, [{ training_step_id: source.id, step_type_id: source.step_type_id, position: 0, repetition_index: 1, planned_duration_seconds: 60, instructions: 'Leve' }]); await trainings.salvar({ id: training.id, user_id: userId, name: 'Novo', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 120 }] }] }); const snapshots = await stepRepo.listar(activity.id); expect(snapshots[0]).toMatchObject({ planned_duration_seconds: 60, instructions: 'Leve' }); expect((await activities.buscarPorId(activity.id))!.training_session_name).toBe('Original'); database.close(); });
  it('abrir editor de treino em execução é bloqueado e após finalizar é liberado', async () => { const { database, userId, trainings, activities } = await setup(); const training = await trainings.salvar({ user_id: userId, name: 'Ativo', blocks: [{ repeat_count: 1, steps: [{ step_type_slug: 'run', duration_seconds: 60 }] }] }); const activity = await activities.criar({ user_id: userId, activity_type_slug: 'structured', training_session_id: training.id, started_at: new Date() }); expect(await trainings.estaEmExecucao(training.id)).toBe(true); await activities.atualizarMetricas(activity.id, { activity_status_slug: 'finished', finished_at: new Date(), elapsed_duration_seconds: 60, moving_duration_seconds: 60, distance_meters: 1 }); expect(await trainings.estaEmExecucao(training.id)).toBe(false); database.close(); });
});
