import { ActivityEngine } from '@/activity/engine';
import { expandTrainingBlocks, TrainingEngine } from '@/activity/training-engine';
import { announceTrainingFinished } from '@/activity/training-guidance';
import { runMigrations } from '@/database/migrations';
import { NodeSQLiteAdapter } from '@/database/node-adapter';
import { ActivitiesRepository, ActivityPointsRepository, ActivitySplitsRepository, ActivityStepsRepository, LookupRepository, TrainingSessionsRepository } from '@/database/repositories';
import { bootstrapLocalUser, seedLookups } from '@/database/seeds';
import * as Haptics from 'expo-haptics';
import * as Speech from 'expo-speech';

async function setup() { const database=new NodeSQLiteAdapter(); await runMigrations(database); await seedLookups(database); const userId=await bootstrapLocalUser(database); const lookups=new LookupRepository(database); await lookups.carregar(); const training=await new TrainingSessionsRepository(database,lookups).salvar({user_id:userId,name:'Canônico',blocks:[{repeat_count:1,steps:[{step_type_slug:'walk',duration_seconds:300,instructions:'Aqueça'}]},{repeat_count:6,steps:[{step_type_slug:'run',duration_seconds:120,instructions:'Corra'},{step_type_slug:'walk',duration_seconds:120,instructions:'Caminhe'}]},{repeat_count:1,steps:[{step_type_slug:'walk',duration_seconds:300,instructions:'Desaqueça'}]}]}); return {database,userId,training}; }

describe('fase 17 — motor de treino',()=>{
  it('o treino canônico expande em 14 etapas, ordenado e com repetition_index 1..6',()=>{ const blocks=[{position:2,repeat_count:1,steps:[{id:4,step_type_id:1,position:0,duration_seconds:300,instructions:null}]},{position:0,repeat_count:1,steps:[{id:1,step_type_id:1,position:0,duration_seconds:300,instructions:null}]},{position:1,repeat_count:6,steps:[{id:3,step_type_id:1,position:1,duration_seconds:120,instructions:null},{id:2,step_type_id:1,position:0,duration_seconds:120,instructions:null}]}]; const expanded=expandTrainingBlocks(blocks); expect(expanded).toHaveLength(14); expect(expanded.map(s=>s.position)).toEqual([...Array(14).keys()]); expect(expanded.slice(1,13).filter((_,i)=>i%2===0).map(s=>s.repetition_index)).toEqual([1,2,3,4,5,6]); expect(expanded.map(s=>s.training_step_id).slice(0,4)).toEqual([1,2,3,2]); });
  it('cria 14 snapshots atômicos, copiados e not_performed, iniciando a primeira',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); const steps=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(steps).toHaveLength(14); expect(steps[0]).toMatchObject({instructions:'Aqueça',planned_duration_seconds:300,status_slug:'not_performed',started_at:new Date(0)}); expect(steps.every(s=>s.status_slug==='not_performed')).toBe(true); database.close(); });
  it('aplica todas as transições de background em ordem, sem pular ou duplicar',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await engine.advanceTraining(new Date(2040_000)); const rows=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(rows.every(s=>s.status_slug==='completed')).toBe(true); expect(rows.map(s=>s.actual_duration_seconds).reduce((a,b)=>a+b,0)).toBe(2040); expect(rows.map(s=>s.position)).toEqual([...Array(14).keys()]); database.close(); });
  it('pula com duração real, preserva distância e continua zerado na próxima',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await engine.skipTrainingStep(new Date(42_000)); const rows=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(rows[0]).toMatchObject({status_slug:'skipped',actual_duration_seconds:42,distance_meters:0}); expect(rows[1]!.started_at).toEqual(new Date(42_000)); expect((await engine.advanceTraining(new Date(42_000)))!.elapsedSeconds).toBe(0); expect(engine.metrics().distance).toBe(0); database.close(); });
  it('pausa congela etapa e exclui a pausa da duração real',async()=>{ const {database,userId,training}=await setup(); let now=0; const engine=new ActivityEngine(database,{clock:{now:()=>now}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); now=100_000; await engine.pause(); now=1000_000; await engine.resume(); now=1200_000; await engine.advanceTraining(new Date(now)); const rows=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(rows[0]).toMatchObject({status_slug:'completed',actual_duration_seconds:300}); expect(rows[0]!.finished_at).toEqual(new Date(1200_000)); database.close(); });
  it('duração real concluída é calculada mesmo quando difere da planejada',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await database.run('UPDATE activity_steps SET planned_duration_seconds=? WHERE activity_id=? AND position=0',[300.5,activity.id]); await engine.advanceTraining(new Date(301_000)); const [step]=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(step).toMatchObject({status_slug:'completed',planned_duration_seconds:300.5,actual_duration_seconds:301}); database.close(); });
  it('encerrar no meio pula somente a corrente e preserva as concluídas',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await engine.advanceTraining(new Date(300_000)); await engine.finish(new Date(330_000)); const counts=await new ActivityStepsRepository(database).contarPorStatus(activity.id); expect(counts).toEqual({completed:1,skipped:1,not_performed:12}); database.close(); });
  it('a atividade encerrada no meio é válida no histórico com percurso e splits',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await new ActivityPointsRepository(database).inserir([{activity_id:activity.id,latitude:-3.73,longitude:-38.52,accuracy:5,recorded_at:new Date(0),is_valid:true},{activity_id:activity.id,latitude:-3.72,longitude:-38.52,accuracy:5,recorded_at:new Date(300_000),is_valid:true}]); await new ActivitySplitsRepository(database).registrar(activity.id,1,300,300,new Date(300_000)); await engine.finish(new Date(330_000)); const saved=await new ActivitiesRepository(database).buscarPorId(activity.id); expect(saved).toMatchObject({id:activity.id,training_session_name:'Canônico'}); expect(await new ActivityPointsRepository(database).listarValidos(activity.id)).toHaveLength(2); expect(await new ActivitySplitsRepository(database).listar(activity.id)).toHaveLength(1); database.close(); });
  it('a soma das distâncias das etapas bate com a distância da atividade',async()=>{ const {database,userId,training}=await setup(); const activityEngine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await activityEngine.startStructuredRun(userId,training.id,training.name,new Date(0)); const stepsEngine=new TrainingEngine(database,activity.id); await stepsEngine.addDistance(125.25); await stepsEngine.advance(new Date(300_000)); await stepsEngine.addDistance(74.75); await database.run('UPDATE activities SET distance_meters=? WHERE id=?',[200,activity.id]); const rows=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(rows[0]!.distance_meters).toBeCloseTo(125.25); expect(rows[1]!.distance_meters).toBeCloseTo(74.75); expect(rows.reduce((sum,row)=>sum+row.distance_meters,0)).toBeCloseTo((await new ActivitiesRepository(database).buscarPorId(activity.id))!.distance_meters); database.close(); });
  it('emite fim uma vez e somente depois de persistir a última etapa',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); let calls=0; let lastStatus=''; engine.onTrainingFinished(async()=>{calls+=1; lastStatus=(await new ActivityStepsRepository(database).listarResultado(activity.id)).at(-1)!.status_slug;}); await engine.advanceTraining(new Date(2040_000)); await engine.advanceTraining(new Date(3000_000)); expect(calls).toBe(1); expect(lastStatus).toBe('completed'); expect(engine.status).toBe('in_progress'); database.close(); });
  it('a UI pode assinar antes do início e a orientação consome o evento de fim',async()=>{ const {database,userId,training}=await setup(); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); let uiConsumed=false; engine.onTrainingFinished(async()=>{uiConsumed=true; await announceTrainingFinished(database);}); await engine.startStructuredRun(userId,training.id,training.name,new Date(0)); await engine.advanceTraining(new Date(2040_000)); expect(uiConsumed).toBe(true); expect(Haptics.notificationAsync).toHaveBeenCalledWith(Haptics.NotificationFeedbackType.Success); expect(Speech.speak).toHaveBeenCalledWith('Treino concluído.',{language:'pt-BR'}); database.close(); });
  it('reconstrói do banco sem reexecutar etapa concluída',async()=>{ const {database,userId,training}=await setup(); const first=new ActivityEngine(database,{clock:{now:()=>0}}); const activity=await first.startStructuredRun(userId,training.id,training.name,new Date(0)); await first.advanceTraining(new Date(300_000)); const restored=new ActivityEngine(database,{clock:{now:()=>310_000}}); await restored.restoreLastActivity(); const snapshot=await restored.recoverySnapshot(); expect(snapshot!.currentStep!.position).toBe(2); const rows=await new ActivityStepsRepository(database).listarResultado(activity.id); expect(rows[0]!.status_slug).toBe('completed'); expect(rows[1]!.started_at).toEqual(new Date(300_000)); database.close(); });
  it('falha no snapshot reverte também a atividade',async()=>{ const {database,userId,training}=await setup(); await database.exec("CREATE TRIGGER fail_steps BEFORE INSERT ON activity_steps BEGIN SELECT RAISE(ABORT,'falha'); END"); const engine=new ActivityEngine(database,{clock:{now:()=>0}}); await expect(engine.startStructuredRun(userId,training.id,training.name,new Date(0))).rejects.toThrow(); expect(await database.all('SELECT id FROM activities')).toEqual([]); database.close(); });
});
