import { useLocalSearchParams, useNavigation, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, PanResponder, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { BottomSheet, Button, Screen, SectionHeader } from '@/components';
import { getStepTypeColor } from '@/constants/theme';
import { getLocalUserId, initializeDatabase } from '@/database';
import { LookupRepository } from '@/database/repositories/lookups';
import { TrainingSessionsRepository, type TrainingSessionTree } from '@/database/repositories/training';
import type { StepType } from '@/database/types';
import { useTheme } from '@/hooks/use-theme';
import { routes } from '@/navigation/routes';
import { calculateEstimatedDuration, formatEditorDuration, groupConsecutiveSteps, removeEditorStep, reorderBlocks, reorderWithinBlock, STEP_TYPE_ORDER, type EditorBlock, type EditorStep, ungroupBlock, updateBlockRepeatCount, updateEditorStep } from '@/training/editor';

let draftKey = 0;
const key = (prefix: string) => `${prefix}-${++draftKey}`;
const toDraft = (training: TrainingSessionTree): EditorBlock[] => training.blocks.map(block => ({ id: block.id, key: `block-${block.id}`, repeatCount: block.repeat_count, steps: block.steps.map(step => ({ id: step.id, key: `step-${step.id}`, stepType: step.step_type, durationSeconds: step.duration_seconds, instructions: step.instructions })) }));

function StepRow({ step, selected, onEdit, onSelect, onRemove, onMove }: { step: EditorStep; selected: boolean; onEdit: () => void; onSelect: () => void; onRemove: () => void; onMove: (delta: -1 | 1) => void }) {
  const theme = useTheme();
  const responder = useMemo(() => PanResponder.create({ onMoveShouldSetPanResponder: (_, gesture) => Math.abs(gesture.dy) > 6, onPanResponderRelease: (_, gesture) => { if (Math.abs(gesture.dy) > 18) onMove(gesture.dy < 0 ? -1 : 1); } }), [onMove]);
  return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={onSelect} style={[styles.step, { backgroundColor: theme.colors.surface, borderColor: selected ? theme.colors.action : theme.colors.border }]}>
    <View accessibilityLabel={`Arrastar ${step.stepType.name}`} accessibilityRole="adjustable" {...responder.panHandlers} style={styles.handle}><Text style={[styles.handleText, { color: theme.colors.textSecondary }]}>≡</Text></View>
    <View style={[styles.accent, { backgroundColor: getStepTypeColor(step.stepType.slug) }]} />
    <Pressable accessibilityLabel={`Editar ${step.stepType.name}`} onPress={event => { event.stopPropagation(); onEdit(); }} style={{ alignItems: 'center', flex: 1, flexDirection: 'row' }}><View style={styles.stepText}><Text style={[styles.stepName, { color: theme.colors.text }]}>{step.stepType.name}</Text>{step.instructions ? <Text numberOfLines={1} style={{ color: theme.colors.textSecondary }}>{step.instructions}</Text> : null}</View><Text style={[styles.duration, { color: theme.colors.text }]}>{formatEditorDuration(step.durationSeconds)}</Text></Pressable>
    <Pressable accessibilityLabel={`Remover ${step.stepType.name}`} hitSlop={8} onPress={event => { event.stopPropagation(); onRemove(); }} style={styles.remove}><Text style={{ color: theme.colors.destructive, fontSize: 20 }}>✕</Text></Pressable>
  </Pressable>;
}

export default function TrainingEditorScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const router = useRouter(); const navigation = useNavigation(); const theme = useTheme();
  const [name, setName] = useState(''); const [blocks, setBlocks] = useState<EditorBlock[]>([]); const [types, setTypes] = useState<StepType[]>([]);
  const [loaded, setLoaded] = useState(!id); const [blocked, setBlocked] = useState(false); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false);
  const [sheet, setSheet] = useState(false); const [selectedType, setSelectedType] = useState<StepType | null>(null); const [minutes, setMinutes] = useState('0'); const [seconds, setSeconds] = useState('0'); const [instructions, setInstructions] = useState(''); const [stepError, setStepError] = useState('');
  const [repeatCount, setRepeatCount] = useState('2'); const [groupError, setGroupError] = useState(''); const [focusedBlock, setFocusedBlock] = useState<string | null>(null); const allowLeave = useRef(false);
  const [editingStepKey, setEditingStepKey] = useState<string | null>(null);

  useEffect(() => { let active = true; void initializeDatabase().then(async database => { const lookups = new LookupRepository(database); const activeTypes = (await lookups.tiposDeEtapaAtivos()).sort((a, b) => STEP_TYPE_ORDER.indexOf(a.slug) - STEP_TYPE_ORDER.indexOf(b.slug)); if (!active) return; setTypes(activeTypes); setSelectedType(activeTypes[0] ?? null); if (id) { const repository = new TrainingSessionsRepository(database, lookups); if (await repository.estaEmExecucao(Number(id))) { setBlocked(true); setLoaded(true); return; } const training = await repository.buscarPorId(Number(id)); if (training) { setName(training.name); setBlocks(toDraft(training)); } setLoaded(true); } }); return () => { active = false; }; }, [id]);
  useEffect(() => navigation.addListener('beforeRemove', event => { if (!dirty || allowLeave.current) return; event.preventDefault(); Alert.alert('Alterações pendentes', 'Deseja sair sem salvar? Nenhuma alteração será persistida.', [{ text: 'Continuar editando', style: 'cancel' }, { text: 'Sair sem salvar', style: 'destructive', onPress: () => { allowLeave.current = true; navigation.dispatch(event.data.action); } }]); }), [dirty, navigation]);

  const estimated = calculateEstimatedDuration(blocks); const selectedKeys = blocks.flatMap(block => block.steps.filter(step => step.selected).map(step => step.key)); const validName = name.trim().length > 0; const canSave = validName && blocks.length > 0 && !saving && !blocked;
  const changeBlocks = useCallback((update: (current: EditorBlock[]) => EditorBlock[]) => { setBlocks(current => update(current)); setDirty(true); }, []);
  const toggle = (stepKey: string) => changeBlocks(current => current.map(block => ({ ...block, steps: block.steps.map(step => step.key === stepKey ? { ...step, selected: !step.selected } : step) })));
  const remove = (blockKey: string, stepKey: string) => changeBlocks(current => removeEditorStep(current, blockKey, stepKey));
  const move = (block: EditorBlock, stepIndex: number, delta: -1 | 1) => changeBlocks(current => block.steps.length > 1 ? reorderWithinBlock(current, block.key, stepIndex, stepIndex + delta) : reorderBlocks(current, current.findIndex(item => item.key === block.key), current.findIndex(item => item.key === block.key) + delta));
  const openSheet = () => { setEditingStepKey(null); setStepError(''); setMinutes('0'); setSeconds('0'); setInstructions(''); setSheet(true); };
  const editStep = (step: EditorStep) => { setEditingStepKey(step.key); setSelectedType(step.stepType); setMinutes(String(Math.floor(step.durationSeconds / 60))); setSeconds(String(step.durationSeconds % 60)); setInstructions(step.instructions ?? ''); setStepError(''); setSheet(true); };
  const addStep = () => { const durationSeconds = Number(minutes || 0) * 60 + Number(seconds || 0); if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) { setStepError('A duração precisa ser maior que zero'); return; } if (!selectedType) return; const values = { stepType: selectedType, durationSeconds: Math.floor(durationSeconds), instructions: instructions.trim() || null }; if (editingStepKey) changeBlocks(current => updateEditorStep(current, editingStepKey, values)); else { const step: EditorStep = { key: key('step'), ...values }; changeBlocks(current => { const focus = focusedBlock && current.find(block => block.key === focusedBlock); return focus ? current.map(block => block.key === focusedBlock ? { ...block, steps: [...block.steps, step] } : block) : [...current, { key: key('block'), repeatCount: 1, steps: [step] }]; }); } setSheet(false); setEditingStepKey(null); };
  const group = () => { try { changeBlocks(current => groupConsecutiveSteps(current, selectedKeys, Number(repeatCount), key('block'))); setGroupError(''); } catch (error) { setGroupError(error instanceof Error ? error.message : 'Não foi possível agrupar'); } };
  const save = async () => { if (!canSave) return; setSaving(true); try { const database = await initializeDatabase(); await new TrainingSessionsRepository(database).salvar({ id: id ? Number(id) : undefined, user_id: getLocalUserId(), name, blocks: blocks.map(block => ({ repeat_count: block.repeatCount, steps: block.steps.map(step => ({ step_type_id: step.stepType.id, duration_seconds: step.durationSeconds, instructions: step.instructions })) })) }); allowLeave.current = true; router.replace(routes.trainingLibrary); } catch (error) { Alert.alert('Treino não salvo', error instanceof Error ? error.message : 'Não foi possível salvar o treino.'); setSaving(false); } };

  if (!loaded) return <Screen canGoBack title={id ? 'Editar treino' : 'Novo treino'}><Text style={{ color: theme.colors.textSecondary }}>Carregando…</Text></Screen>;
  if (blocked) return <Screen canGoBack title="Editar treino"><View style={styles.blocked}><Text style={[styles.blockedTitle, { color: theme.colors.text }]}>Treino em execução</Text><Text style={{ color: theme.colors.textSecondary, textAlign: 'center' }}>Finalize a atividade atual antes de editar este treino.</Text></View></Screen>;
  return <Screen canGoBack headerAction={<Pressable accessibilityRole="button" accessibilityState={{ disabled: !canSave }} disabled={!canSave} onPress={() => void save()}><Text style={{ color: theme.colors.action, fontSize: 17, fontWeight: '700', opacity: canSave ? 1 : 0.4 }}>Salvar</Text></Pressable>} scrollable={false} title={id ? 'Editar treino' : 'Novo treino'}>
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.label, { color: theme.colors.textSecondary }]}>NOME</Text><TextInput accessibilityLabel="Nome do treino" onChangeText={value => { setName(value); setDirty(true); }} placeholder="Ex.: Intervalado iniciante" placeholderTextColor={theme.colors.textSecondary} style={[styles.input, { borderColor: validName ? theme.colors.border : theme.colors.destructive, color: theme.colors.text }]} value={name} />{!validName ? <Text style={{ color: theme.colors.destructive }}>Informe um nome para o treino</Text> : null}<SectionHeader title="ETAPAS" />
      {blocks.length === 0 ? <Text style={[styles.empty, { color: theme.colors.textSecondary }]}>Adicione a primeira etapa</Text> : blocks.map(block => <View key={block.key} style={block.repeatCount > 1 ? [styles.block, { borderColor: focusedBlock === block.key ? theme.colors.action : theme.colors.border }] : undefined}>{block.repeatCount > 1 ? <Pressable onPress={() => setFocusedBlock(value => value === block.key ? null : block.key)} style={styles.blockHeader}><View style={{ alignItems: 'center', flexDirection: 'row', gap: 10 }}><Pressable accessibilityLabel="Diminuir repetições" disabled={block.repeatCount <= 2} onPress={() => changeBlocks(current => updateBlockRepeatCount(current, block.key, block.repeatCount - 1))}><Text style={{ color: theme.colors.action, fontSize: 22 }}>−</Text></Pressable><Text style={[styles.blockTitle, { color: theme.colors.text }]}>{block.repeatCount}× repetições</Text><Pressable accessibilityLabel="Aumentar repetições" onPress={() => changeBlocks(current => updateBlockRepeatCount(current, block.key, block.repeatCount + 1))}><Text style={{ color: theme.colors.action, fontSize: 22 }}>+</Text></Pressable></View><Pressable onPress={() => changeBlocks(current => ungroupBlock(current, block.key))}><Text style={{ color: theme.colors.action, fontWeight: '700' }}>Desagrupar</Text></Pressable></Pressable> : null}{block.steps.map((step, stepIndex) => <StepRow key={step.key} onEdit={() => editStep(step)} onMove={delta => move(block, stepIndex, delta)} onRemove={() => remove(block.key, step.key)} onSelect={() => toggle(step.key)} selected={Boolean(step.selected)} step={step} />)}</View>)}
      {selectedKeys.length >= 2 ? <View style={[styles.groupBox, { borderColor: theme.colors.border }]}><TextInput accessibilityLabel="Repetições" keyboardType="number-pad" onChangeText={setRepeatCount} style={[styles.repeatInput, { borderColor: theme.colors.border, color: theme.colors.text }]} value={repeatCount} /><Button onPress={group} variant="secondary">Agrupar em bloco</Button>{groupError ? <Text style={{ color: theme.colors.destructive }}>{groupError}</Text> : null}</View> : null}<Button onPress={openSheet} variant="secondary">+ Adicionar etapa</Button></ScrollView>
    <View style={[styles.estimated, { borderColor: theme.colors.border }]}><Text style={[styles.label, { color: theme.colors.textSecondary }]}>DURAÇÃO ESTIMADA</Text><Text style={[styles.total, { color: theme.colors.text }]}>{formatEditorDuration(estimated)}</Text></View>
    <BottomSheet footer={<Button onPress={addStep}>{editingStepKey ? 'Salvar alteração' : 'Adicionar'}</Button>} onDismiss={() => { setSheet(false); setEditingStepKey(null); }} visible={sheet}><Text style={[styles.sheetTitle, { color: theme.colors.text }]}>{editingStepKey ? 'Editar etapa' : 'Nova etapa'}</Text><Text style={[styles.label, { color: theme.colors.textSecondary }]}>TIPO</Text><View style={styles.typeList}>{types.map(type => <Pressable accessibilityRole="radio" accessibilityState={{ selected: selectedType?.id === type.id }} key={type.id} onPress={() => setSelectedType(type)} style={[styles.type, { borderColor: selectedType?.id === type.id ? getStepTypeColor(type.slug) : theme.colors.border }]}><View style={[styles.typeDot, { backgroundColor: getStepTypeColor(type.slug) }]} /><Text style={{ color: theme.colors.text }}>{type.name}</Text></Pressable>)}</View><Text style={[styles.label, { color: theme.colors.textSecondary }]}>DURAÇÃO</Text><View style={styles.timeRow}><TextInput accessibilityLabel="Minutos" keyboardType="number-pad" onChangeText={setMinutes} style={[styles.timeInput, { borderColor: theme.colors.border, color: theme.colors.text }]} value={minutes} /><Text style={{ color: theme.colors.textSecondary }}>min</Text><TextInput accessibilityLabel="Segundos" keyboardType="number-pad" onChangeText={setSeconds} style={[styles.timeInput, { borderColor: theme.colors.border, color: theme.colors.text }]} value={seconds} /><Text style={{ color: theme.colors.textSecondary }}>s</Text></View>{stepError ? <Text style={{ color: theme.colors.destructive }}>{stepError}</Text> : null}<TextInput accessibilityLabel="Instrução opcional" multiline onChangeText={setInstructions} placeholder="Instrução opcional" placeholderTextColor={theme.colors.textSecondary} style={[styles.instruction, { borderColor: theme.colors.border, color: theme.colors.text }]} value={instructions} /></BottomSheet>
  </Screen>;
}

const styles = StyleSheet.create({ content: { gap: 10, paddingBottom: 24 }, label: { fontSize: 12, fontWeight: '700', letterSpacing: 1.3, marginTop: 8 }, input: { borderRadius: 12, borderWidth: 1, fontSize: 18, minHeight: 50, paddingHorizontal: 14 }, empty: { paddingVertical: 28, textAlign: 'center' }, step: { alignItems: 'center', borderRadius: 14, borderWidth: 1, flexDirection: 'row', minHeight: 62, overflow: 'hidden' }, handle: { alignItems: 'center', justifyContent: 'center', minHeight: 54, width: 42 }, handleText: { fontSize: 24 }, accent: { alignSelf: 'stretch', width: 5 }, stepText: { flex: 1, gap: 2, paddingHorizontal: 12 }, stepName: { fontSize: 17, fontWeight: '600' }, duration: { fontFamily: 'monospace', fontSize: 16 }, remove: { alignItems: 'center', justifyContent: 'center', minHeight: 44, width: 44 }, block: { borderRadius: 16, borderWidth: 1, gap: 8, padding: 10 }, blockHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 36 }, blockTitle: { fontSize: 17, fontWeight: '700' }, groupBox: { borderRadius: 14, borderWidth: 1, gap: 8, padding: 12 }, repeatInput: { borderRadius: 10, borderWidth: 1, fontSize: 18, minHeight: 44, paddingHorizontal: 12 }, estimated: { alignItems: 'center', borderColor: 'transparent', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 10, paddingTop: 12 }, total: { fontFamily: 'monospace', fontSize: 27, fontWeight: '700' }, sheetTitle: { fontSize: 25, fontWeight: '700', marginBottom: 16 }, typeList: { gap: 8, marginVertical: 8 }, type: { alignItems: 'center', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 46, paddingHorizontal: 12 }, typeDot: { borderRadius: 5, height: 10, width: 10 }, timeRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginVertical: 10 }, timeInput: { borderRadius: 10, borderWidth: 1, fontSize: 20, minHeight: 48, paddingHorizontal: 12, textAlign: 'center', width: 72 }, instruction: { borderRadius: 12, borderWidth: 1, marginTop: 12, minHeight: 72, padding: 12, textAlignVertical: 'top' }, blocked: { alignItems: 'center', flex: 1, gap: 10, justifyContent: 'center' }, blockedTitle: { fontSize: 25, fontWeight: '700' } });
